[2024-04-16T04:31:31.817+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.parse_apod_data scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-04-16T04:31:31.826+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.parse_apod_data scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-04-16T04:31:31.827+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-16T04:31:31.828+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-04-16T04:31:31.828+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-16T04:31:31.852+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): parse_apod_data> on 2024-02-28 00:00:00+00:00
[2024-04-16T04:31:31.861+0000] {standard_task_runner.py:55} INFO - Started process 1274 to run task
[2024-04-16T04:31:31.866+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'parse_apod_data', 'scheduled__2024-02-28T00:00:00+00:00', '--job-id', '1234', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmpu_v7z55q']
[2024-04-16T04:31:31.866+0000] {standard_task_runner.py:83} INFO - Job 1234: Subtask parse_apod_data
[2024-04-16T04:31:31.917+0000] {task_command.py:376} INFO - Running <TaskInstance: first_dag.parse_apod_data scheduled__2024-02-28T00:00:00+00:00 [running]> on host b0ce51d36eb8
[2024-04-16T04:31:31.984+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=parse_apod_data
AIRFLOW_CTX_EXECUTION_DATE=2024-02-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-28T00:00:00+00:00
[2024-04-16T04:31:31.985+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/FirstDag.py", line 32, in parse_apod_data
    title=row.get('title'),
AttributeError: 'str' object has no attribute 'get'
[2024-04-16T04:31:31.991+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=parse_apod_data, execution_date=20240228T000000, start_date=20240416T043131, end_date=20240416T043131
[2024-04-16T04:31:31.998+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1234 for task parse_apod_data ('str' object has no attribute 'get'; 1274)
[2024-04-16T04:31:32.037+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-04-16T04:31:32.065+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
